site_name: meel0wx's Blog
repo_url: https://github.com/meel0wx/meel0wx.github.io
repo_name: meel0wx/meel0wx.github.io

theme:
  name: material
  logo: assets/android-chrome-192x192.png
  favicon: assets/favicon.ico
  # custom_dir: ovverides
  features:
    # - navigation.tabs
    # - navigation.sections
    # - toc.integrate
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.indexes
    - navigation.footer
    # - search.suggest
    # - search.highlight
    # - content.tabs.link
    - content.code.copy
    - content.code.select
    - content.code.annotate
    
  language: en
  icon:
    logo: brand/logo
    repo: fontawesome/brands/github
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css:  fontawesome/brands/css3
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: carbon
      accent: purple
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: carbon
      accent: lime

# nav:
#   - Home: index.md


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/meel0wx
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/meel0wx
    # - icon: fontawesome/brands/linkedin
  tags:
    HTML5: html
    JavaScript: js
    CSS: css

plugins:
  - search:
      lang: en
  - tags:
      tags_file: tags.md
  - git-revision-date-localized:
      enable_creation_date: true
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
